openapi: 3.0.0
servers:
  - description: localhost
    url: 'http://localhost:5000/api/'
info:
  description: MyCivi API Implementation
  version: 1.0.0
  title: MyCivi
tags:
  - name: user
    description: Operations about user
paths:
  /welcome/signup:
    post:
      tags:
        - user
      summary: adds a user
      operationId: signup.create
      description: Adds a user to the system
      responses:
        '200':
          description: OK
        '201':
          description: Created
        '500':
          description: 500 Internal server error
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  example: 500 Internal server error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserData'
        required: true
        description: User to add
  /welcome/login:
    post:
      tags:
        - user
      summary: post a user that already signed up
      operationId: login.enter
      description: login user
      responses:
        '200':
          description: OK
        '201':
          description: Created
        '500':
          description: 500 Internal server error
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  example: 500 Internal server error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginUser'
        required: true

  /user/{username}:
    post:
      tags:
        - user
      summary: add public user data
      operationId: user.input
      description: Adds public user data to the system
      parameters:
        - in: path
          name: username
          description: identitas user
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        '200':
          description: OK
        '201':
          description: Created
        '500':
          description: 500 Internal server error
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  example: 500 Internal server error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PublicUserData'
        required: true
        description: Public user data to add
    put:
      tags:
        - user
      summary: edit public user data
      operationId: user.update
      description: Edits public user data from the system
      parameters:
        - in: path
          name: username
          description: identitas user
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        '200':
          description: OK
        '201':
          description: Created
        '500':
          description: 500 Internal server error
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  example: 500 Internal server error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PublicUserData'
        required: true
        description: Public user data to edit

  /user/list:
    get:
      summary: Melihat semua data user yang ada
      operationId: list.read_all
      description: |
        Melihat semua data user
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/PublicUserData'
        '401':
          description: 401 Access unauthorized
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  example: 401 Access unauthorized
        '403':
          description: 403 Access forbidden
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  example: 403 Access forbidden
        '404':
          description: 404 Not Found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  example: 404 Not Found
        '500':
          description: 500 Internal server error
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  example: 500 Internal server error

  /user/list/{username}:
    get:
      summary: Melihat data user berdasarkan username
      operationId: list.read_one
      description: |
        Melihat data user berdasarkan username
      parameters:
        - in: path
          name: username
          description: identitas user
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/PublicUserData'
        '401':
          description: 401 Access unauthorized
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  example: 401 Access unauthorized
        '403':
          description: 403 Access forbidden
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  example: 403 Access forbidden
        '404':
          description: 403 Not Found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  example: 403 Not Found
        '500':
          description: 500 Internal server error
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  example: 500 Internal server error
components:
  schemas:
    UserData:
      type: object
      required:
        - username
        - email
        - password
      properties:
        username:
          type: string
          example: leo
        email:
          type: string
          example: leo.draconus@gmail.com
        password:
          type: string
          format: password
          example: qwerty
        publicdata:
          $ref: '#/components/schemas/PublicUserData'

    LoginUser:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
          example: leo
        password:
          type: string
          format: password
          example: qwerty

    PublicUserData:
      type: object
      required:
        - nama
        - bidang
        - prestasi
      properties:
        nama:
          type: string
          example: Leo Draconus
        bidang:
          type: string
          example: musik
        prestasi:
          type: string
          example: juara 2 lomba gitar akustik
